# Generated by Django 5.0.6 on 2026-03-04 13:23

import apps.properties.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name e.g. 'wifi', 'car'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'db_table': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('penthouse', 'Penthouse'), ('office', 'Office')], default='apartment', max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('floor_number', models.PositiveSmallIntegerField(default=0)),
                ('house_number', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold'), ('maintenance', 'Under Maintenance')], default='available', max_length=15)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity')),
                ('listed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.properties.models.image_upload_path)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=apps.properties.models.thumbnail_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_properties',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'status'], name='properties_city_6c1708_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'status'], name='properties_propert_08af30_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price', 'bedrooms'], name='properties_price_7368ce_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured', '-created_at'], name='properties_is_feat_8e4aed_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties_status_e6008a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together={('user', 'property')},
        ),
    ]
